version: '3.2'
services:
    disa-api-integ:
        build:
            context: .
            dockerfile: ./integ/Dockerfile
        container_name: disa-api-integ
        ports:
            - "8085:8080"
            - "8001:8001"
        networks:
            - network
        depends_on:
            - "disa-api-db"
        volumes:
          - type: bind
            source: /opt/disa/data
            target: /opt/disa/data
        restart: unless-stopped

    disa-weekly-report:
        image: disa-weekly-report:2.3.1-SNAPSHOT
        container_name: disa-weekly-report
        networks:
            - network
        depends_on:
            - "disa-api-db"
        restart: unless-stopped
        environment:
            - DISA_DATASOURCE_URL=
            - DISA_DATASOURCE_USERNAME=
            - DISA_DATASOURCE_PASSWORD=
            - DISA_MAIL_USERNAME=
            - DISA_NOTIFICATION_CRON=
            - DISA_NOTIFIER_URL=

    disa-notifier:
        image: disa-notifier:1.0.1-SNAPSHOT
        container_name: disa-notifier
        ports:
            - "8571:8571"
        networks:
            - network
        restart: unless-stopped
        environment:
            - DISA_MAIL_HOST=
            - DISA_MAIL_PORT=
            - DISA_MAIL_USERNAME=
            - DISA_MAIL_PASSWORD=

    disa-api-db:
        build:
            context: ./database
        container_name: disa-api-db
        ports:
            - "3310:3306"
        networks:
            - network
        volumes:
            - type: volume
              source: dbdata
              target: /opt/disa/data
        restart: unless-stopped

networks:
  network:
    driver: bridge

volumes:
  dbdata:
